site_name: Instance2d Docs
site_dir: C:/projects/.html_.js/Instance2d/Instance2d/documentation

nav:
  - README: index.md
  - Home: Home.md
  - Examples: Examples.md
  - Data/Enum: Data.md
  - Game: Game.md
  - Services:
    - Screen: Screen.md
    - Instance: Instance.md
    - RunService: RunService.md
    - InputService: InputService.md
    - RenderService: RenderService.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  logo: https://instance2d.js.org/images/Favicon.svg

  features:
    - navigation.tabs
    - navigations.sections
    - toc.intergrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - scheme: default

      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

      primary: darkpurple
      accent: purple
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: darkpurple
      accent: lime